# Generated by Django 5.2.5 on 2025-11-02 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='marksrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='proctorprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='proctorprofile',
            name='office_phone',
        ),
        migrations.RemoveField(
            model_name='section',
            name='branch',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attended_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proctorprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='total_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='CSE', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksrecord',
            name='exam_name',
            field=models.CharField(choices=[('Internal 1', 'Internal 1'), ('Internal 2', 'Internal 2'), ('Total Internal', 'Total Internal'), ('External', 'External')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marksrecord',
            name='marks_obtained',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='marksrecord',
            name='max_marks',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(default='CSE', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='proctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proctored_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='usn',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remarks', models.TextField()),
                ('proctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
