# Generated by Django 5.2.5 on 2025-11-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_helpmessage_remove_attendancerecord_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
