# Generated by Django 5.2.5 on 2025-11-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studentprofile_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marksrecord',
            old_name='marks_obtained',
            new_name='internal_1',
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='internal_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='total_external',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='total_internal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='marksrecord',
            name='exam_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
