# Generated by Django 5.2.5 on 2025-11-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='attended_classes',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attended',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='total_classes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
