# Generated by Django 5.2.5 on 2025-11-11 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_studentprofile_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meetingrecord',
            name='proctor',
        ),
        migrations.RemoveField(
            model_name='meetingrecord',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='meetingrecord',
            name='student',
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proctorprofile'),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='students',
            field=models.ManyToManyField(related_name='meetings', to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='title',
            field=models.CharField(default='General Meeting', max_length=200),
            preserve_default=False,
        ),
    ]
