# Generated by Django 5.2.5 on 2025-11-11 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_meetingmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='marksrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='marksrecord',
            name='exam_name',
        ),
        migrations.RemoveField(
            model_name='marksrecord',
            name='internal_1',
        ),
        migrations.RemoveField(
            model_name='marksrecord',
            name='internal_2',
        ),
        migrations.RemoveField(
            model_name='marksrecord',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='marksrecord',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='marksrecord',
            name='total_external',
        ),
        migrations.RemoveField(
            model_name='marksrecord',
            name='total_internal',
        ),
        migrations.RemoveField(
            model_name='marksrecord',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attended_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='external',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='internal1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='internal2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='total_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
