# Generated by Django 5.2.5 on 2025-11-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_attendancerecord_attended_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='meetingrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.proctorprofile'),
        ),
        migrations.AlterField(
            model_name='meetingrecord',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
