# Generated by Django 5.2.5 on 2025-11-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_broadcastmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='department',
        ),
    ]
