# Generated by Django 5.2.5 on 2025-11-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_hodprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
