# Generated by Django 5.2.5 on 2025-11-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_broadcastmessage_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksrecord',
            name='attendance_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='total_internal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marksrecord',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
    ]
