# Generated by Django 5.2.5 on 2025-11-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_marksrecord_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksrecord',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
